version: "3.8"

volumes:
  postgres_data: {}

services:
  db:
    container_name: supabase-db
    image: supabase/postgres:15.1.0.147
    # networks:
    #   - afterclass
    healthcheck:
      test: pg_isready -U postgres -h localhost
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal # prevents Realtime polling queries from appearing in logs
    restart: unless-stopped
    ports:
      # Pass down internal port because it's set dynamically by other services
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: ${POSTGRES_PORT}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
    volumes:
      # - ./.docker/volumes/db/init/data.sql:/docker-entrypoint-initdb.d/init-scripts/99-data.sql:Z
      # # PGDATA directory is persisted between restarts
      # - ./.docker/volumes/db/data:/var/lib/postgresql/data:Z
      - postgres_data:/var/lib/postgresql/data
      # # Must be superuser to alter reserved role
      - ./.docker/volumes/db/roles.sql:/docker-entrypoint-initdb.d/init-scripts/99-roles.sql:Z
