import { type VariantProps, tv } from "tailwind-variants";
export type SearchResultVariants = VariantProps<typeof searchResultTheme>;

export const searchResultTheme = tv(
  {
    slots: {
      root: ["flex", "h-full", "flex-col", "gap-10"],
      title: ["truncate", "text-left"],
      titleIcon: ["text-text-em-mid", "flex-none"],
      content: ["flex", "h-full", "gap-12"],
      list: ["flex", "w-full", "flex-col", "items-start", "gap-4"],
      empty: [
        "w-full",
        "gap-4",
        "items-center",
        "flex",
        "flex-col",
        "rounded-lg",
        "bg-surface-base",
      ],
      item: [
        "flex",
        "h-fit",
        "w-full",
        "items-center",
        "justify-between",
        "rounded-lg",
        "border",
        "border-border-default",
        "bg-surface-base",
      ],
      itemHeadWrapper: ["flex", "items-center", "gap-4", "self-stretch"],
      itemContent: [
        "flex",
        "flex-[1_0_0%]",
        "flex-col",
        "items-start",
        "justify-center",
      ],
      itemSchoolIcon: ["mt-[2px]", "flex-none", "text-primary-default"],
      itemArrow: ["flex-none", "text-text-em-mid"],
      itemTitle: ["text-left", "tracking-tight", "text-text-em-mid"],
      itemSubtitle: ["tracking-tight", "text-text-em-low", "font-normal"],
      itemStatsWrapper: ["flex", "items-center", "text-text-em-low"],
      divider: ["mx-4", "border-l-2", "border-border-default"],
      filter: [
        "sticky",
        "top-12",
        "flex",
        "h-fit",
        "w-fit",
        "flex-col",
        "items-start gap-12",
      ],
      filterField: ["w-fit"],
      filterToggleGroup: ["border-border-default"],
      filterToggleGroupItem: [],
    },
    variants: {
      show: {
        false: {
          empty: ["hidden"],
        },
      },
      size: {
        sm: {
          empty: ["p-4", "py-8", "text-sm"],
          item: ["p-3", "gap-2"],
          itemContent: ["gap-2"],
          itemTitle: ["text-sm"],
          itemSubtitle: ["text-sm"],
          itemStatsWrapper: ["gap-2"],
          itemSchoolIcon: ["h-4", "w-4"],
          itemArrow: ["h-4", "w-4"],
          divider: ["hidden"],
          filter: ["hidden"],
        },
        md: {
          empty: ["p-8", "px-16"],
          item: ["p-4", "gap-4"],
          itemContent: ["gap-4"],
          itemTitle: ["text-lg"],
          itemSubtitle: ["text-lg"],
          itemStatsWrapper: ["gap-4"],
          itemSchoolIcon: ["h-6", "w-6"],
          itemArrow: ["h-6", "w-6"],
          divider: ["block"],
          filter: ["block"],
        },
      },
    },
  },
  { responsiveVariants: true },
);
