import { tv, type VariantProps } from "tailwind-variants";

export const sidebarTheme = tv({
  slots: {
    root: [
      "bg-surface-base",
      "text-text-em-mid",
      "flex",
      "h-full",
      "w-[--sidebar-width]",
      "flex-col",
    ],
    rootCollapsibleMobileSheetContent: [
      "bg-surface-base",
      "text-text-em-mid",
      "w-[--sidebar-width]",
      "p-0",
      "[&>button]:hidden",
    ],
    rootCollapsibleMobileWrapper: ["flex", "h-full", "w-full", "flex-col"],
    rootCollapsibleWrapper: [
      "text-text-em-mid",
      "group",
      "peer",
      "hidden",
      "md:block",
    ],
    rootCollapsibleSidebarDesktopGap: [
      "relative",
      "h-svh",
      "w-[--sidebar-width]",
      "bg-transparent",
      "transition-[width]",
      "duration-200",
      "ease-linear",
      "group-data-[collapsible=offcanvas]:w-0",
      "group-data-[side=right]:rotate-180",
    ],
    rootCollapsibleSidebarWrapper: [
      "fixed",
      "inset-y-0",
      "z-10",
      "hidden",
      "h-svh",
      "w-[--sidebar-width]",
      "transition-[left,right,width]",
      "duration-200",
      "ease-linear",
      "md:flex",
    ],
    rootCollapsibleSidebar: [
      "bg-surface-base",
      "group-data-[variant=floating]:border-border-default",
      "flex",
      "h-full",
      "w-full",
      "flex-col",
      "group-data-[variant=floating]:rounded-lg",
      "group-data-[variant=floating]:border",
      "group-data-[variant=floating]:shadow",
    ],
    content: [
      "flex",
      "min-h-0",
      "flex-1",
      "flex-col",
      "gap-2",
      "overflow-auto",
      "group-data-[collapsible=icon]:overflow-hidden",
    ],
    footer: ["flex", "flex-col", "gap-2", "p-2"],
    group: ["relative", "flex", "w-full", "min-w-0", "flex-col", "p-2"],
    groupAction: [
      "text-text-em-mid",
      "ring-sidebar-ring",
      "hover:bg-surface-elevated",
      "hover:text-text-em-high",
      "absolute",
      "right-3",
      "top-3.5",
      "flex",
      "aspect-square",
      "w-5",
      "items-center",
      "justify-center",
      "rounded-md",
      "p-0",
      "outline-none",
      "transition-transform",
      "focus-visible:ring-2",
      "[&>svg]:size-4",
      "[&>svg]:shrink-0",
      // Increases the hit area of the button on mobile.
      "after:absolute",
      "after:-inset-2",
      "after:md:hidden",
      "group-data-[collapsible=icon]:hidden",
    ],
    groupContent: ["w-full", "text-sm"],
    groupLabel: [
      "text-text-em-mid/70",
      "ring-sidebar-ring",
      "flex",
      "h-8",
      "shrink-0",
      "items-center",
      "rounded-md",
      "px-2",
      "text-xs",
      "font-medium",
      "outline-none",
      "transition-[margin,opa]",
      "duration-200",
      "ease-linear",
      "focus-visible:ring-2",
      "[&>svg]:size-4",
      "[&>svg]:shrink-0",
      "group-data-[collapsible=icon]:-mt-8",
      "group-data-[collapsible=icon]:opacity-0",
    ],
    header: ["flex", "flex-col", "gap-2", "p-2"],
    input: [
      "bg-bg-base",
      "focus-visible:ring-sidebar-ring",
      "h-8",
      "w-full",
      "shadow-none",
      "focus-visible:ring-2",
    ],
    inset: [
      "bg-bg-base",
      "relative",
      "flex",
      "min-h-svh",
      "flex-1",
      "flex-col",
      "peer-data-[variant=inset]:min-h-[calc(100svh-theme(spacing.4))]",
      "md:peer-data-[variant=inset]:m-2",
      "md:peer-data-[state=collapsed]:peer-data-[variant=inset]:ml-2",
      "md:peer-data-[variant=inset]:ml-0",
      "md:peer-data-[variant=inset]:rounded-xl",
      "md:peer-data-[variant=inset]:shadow",
    ],
    menu: ["flex", "w-full", "min-w-0", "flex-col", "gap-1"],
    menuAction: [
      "text-text-em-mid",
      "ring-sidebar-ring",
      "hover:bg-surface-elevated",
      "hover:text-text-em-high",
      "peer-hover/menu-button:text-text-em-high",
      "absolute",
      "right-1",
      "top-1.5",
      "flex",
      "aspect-square",
      "w-5",
      "items-center",
      "justify-center",
      "rounded-md",
      "p-0",
      "outline-none",
      "transition-transform",
      "focus-visible:ring-2",
      "[&>svg]:size-4",
      "[&>svg]:shrink-0",
      // Increases the hit area of the button on mobile.
      "after:absolute",
      "after:-inset-2",
      "after:md:hidden",
      "peer-data-[size=sm]/menu-button:top-1",
      "peer-data-[size=default]/menu-button:top-1.5",
      "peer-data-[size=lg]/menu-button:top-2.5",
      "group-data-[collapsible=icon]:hidden",
    ],
    menuBadge: [
      "text-text-em-mid",
      "pointer-events-none",
      "absolute",
      "right-1",
      "flex",
      "h-5",
      "min-w-5",
      "select-none",
      "items-center",
      "justify-center",
      "rounded-md",
      "px-1",
      "text-xs",
      "font-medium",
      "tabular-nums",
      "peer-hover/menu-button:text-text-em-high",
      "peer-data-[active=true]/menu-button:text-text-em-high",
      "peer-data-[size=sm]/menu-button:top-1",
      "peer-data-[size=default]/menu-button:top-1.5",
      "peer-data-[size=lg]/menu-button:top-2.5",
      "group-data-[collapsible=icon]:hidden",
    ],
    menuButton: [
      "peer/menu-button",
      "flex",
      "w-full",
      "items-center",
      "gap-2",
      "overflow-hidden",
      "rounded-md",
      "p-2",
      "text-left",
      "text-sm",
      "outline-none",
      "ring-sidebar-ring",
      "transition-[width,height,padding]",
      "hover:bg-surface-elevated",
      "hover:text-text-em-high",
      "focus-visible:ring-2",
      "active:bg-surface-elevated",
      "active:text-text-em-high",
      "disabled:pointer-events-none",
      "disabled:opacity-50",
      "group-has-[[data-sidebar=menu-action]]/menu-item:pr-8",
      "aria-disabled:pointer-events-none",
      "aria-disabled:opacity-50",
      "data-[active=true]:bg-surface-elevated",
      "data-[active=true]:font-medium",
      "data-[active=true]:text-text-em-high",
      "data-[state=open]:hover:bg-surface-elevated",
      "data-[state=open]:hover:text-text-em-high",
      "group-data-[collapsible=icon]:!size-8",
      "group-data-[collapsible=icon]:!p-2",
      "[&>span:last-child]:truncate",
      "[&>svg]:size-4",
      "[&>svg]:shrink-0",
    ],
    menuItem: ["group/menu-item", "relative"],
    menuSkeleton: [
      "flex",
      "h-8",
      "items-center",
      "gap-2",
      "rounded-md",
      "px-2",
    ],
    menuSub: [
      "border-border-default",
      "mx-3.5",
      "flex",
      "min-w-0",
      "translate-x-px",
      "flex-col",
      "gap-1",
      "border-l",
      "px-2.5",
      "py-0.5",
      "group-data-[collapsible=icon]:hidden",
    ],
    menuSubButton: [
      "text-text-em-mid",
      "ring-sidebar-ring",
      "hover:bg-surface-elevated",
      "hover:text-text-em-high",
      "active:bg-surface-elevated",
      "active:text-text-em-high",
      "[&>svg]:text-text-em-high",
      "flex",
      "h-7",
      "min-w-0",
      "-translate-x-px",
      "items-center",
      "gap-2",
      "overflow-hidden",
      "rounded-md",
      "px-2",
      "outline-none",
      "focus-visible:ring-2",
      "disabled:pointer-events-none",
      "disabled:opacity-50",
      "aria-disabled:pointer-events-none",
      "aria-disabled:opacity-50",
      "[&>span:last-child]:truncate",
      "[&>svg]:size-4",
      "[&>svg]:shrink-0",
      "data-[active=true]:bg-surface-elevated",
      "data-[active=true]:text-text-em-high",
      "group-data-[collapsible=icon]:hidden",
    ],
    provider: [
      "group/sidebar-wrapper",
      "has-[[data-variant=inset]]:bg-bg-base",
      "flex",
      "min-h-svh",
      "w-full",
    ],
    rail: [
      "hover:after:bg-border-default",
      "absolute",
      "inset-y-0",
      "z-20",
      "hidden",
      "w-4",
      "-translate-x-1/2",
      "transition-all",
      "ease-linear",
      "after:absolute",
      "after:inset-y-0",
      "after:left-1/2",
      "after:w-[2px]",
      "group-data-[side=left]:-right-4",
      "group-data-[side=right]:left-0",
      "sm:flex",
      "[[data-side=left]_&]:cursor-w-resize",
      "[[data-side=right]_&]:cursor-e-resize",
      "[[data-side=left][data-state=collapsed]_&]:cursor-e-resize",
      "[[data-side=right][data-state=collapsed]_&]:cursor-w-resize",
      "group-data-[collapsible=offcanvas]:hover:bg-surface-base",
      "group-data-[collapsible=offcanvas]:translate-x-0",
      "group-data-[collapsible=offcanvas]:after:left-full",
      "[[data-side=left][data-collapsible=offcanvas]_&]:-right-2",
      "[[data-side=right][data-collapsible=offcanvas]_&]:-left-2",
    ],
    separator: ["bg-border-default", "mx-2", "w-auto"],
    trigger: ["h-7", "w-7", "p-4"],
  },

  variants: {
    showOnHover: {
      true: {
        menuAction: [
          "peer-data-[active=true]/menu-button:text-text-em-high",
          "group-focus-within/menu-item:opacity-100",
          "group-hover/menu-item:opacity-100",
          "data-[state=open]:opacity-100",
          "md:opacity-0",
        ],
      },
    },
    variant: {
      default: {
        menuButton: ["hover:bg-surface-elevated", "hover:text-text-em-high"],
      },
      outline: {
        menuButton: [
          "bg-background",
          "shadow-[0_0_0_1px_hsl(var(--border-default))]",
          "hover:bg-surface-elevated",
          "hover:text-text-em-high",
          "hover:shadow-[0_0_0_1px_hsl(var(--sidebar-accent))]",
        ],
      },
      sidebar: {
        rootCollapsibleSidebarDesktopGap: [
          "group-data-[collapsible=icon]:w-[--sidebar-width-icon]",
        ],
        rootCollapsibleSidebarWrapper: [
          "border-border-default",
          "group-data-[collapsible=icon]:w-[--sidebar-width-icon]",
          "group-data-[side=left]:border-r",
          "group-data-[side=right]:border-l",
        ],
      },
      floating: {
        rootCollapsibleSidebarDesktopGap: [
          "group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)_+_theme(spacing.4))]",
        ],
        rootCollapsibleSidebarWrapper: [
          "p-2",
          "group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)_+_theme(spacing.4)_+2px)]",
        ],
      },
      inset: {
        rootCollapsibleSidebarDesktopGap: [
          "group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)_+_theme(spacing.4))]",
        ],
        rootCollapsibleSidebarWrapper: [
          "p-2",
          "group-data-[collapsible=icon]:w-[calc(var(--sidebar-width-icon)_+_theme(spacing.4)_+2px)]",
        ],
      },
    },
    size: {
      md: {
        menuButton: ["h-8", "text-sm"],
        menuSubButton: ["text-sm"],
      },
      sm: {
        menuButton: ["h-7", "text-xs"],
        menuSubButton: ["text-xs"],
      },
      lg: {
        menuButton: ["h-12", "text-sm", "group-data-[collapsible=icon]:!p-0"],
      },
    },
    side: {
      left: {
        rootCollapsibleSidebarWrapper: [
          "left-0",
          "group-data-[collapsible=offcanvas]:left-[calc(var(--sidebar-width)*-1)]",
        ],
      },
      right: {
        rootCollapsibleSidebarWrapper: [
          "right-0",
          "group-data-[collapsible=offcanvas]:right-[calc(var(--sidebar-width)*-1)]",
        ],
      },
    },
  },
  defaultVariants: {
    variant: "default",
    size: "md",
  },
});

export type SidebarVariants = VariantProps<typeof sidebarTheme>;
