import { type VariantProps, tv } from "tailwind-variants";

export type DropdownMenuVariants = VariantProps<typeof dropdownMenuTheme>;

export const dropdownMenuTheme = tv(
  {
    slots: {
      subtrigger: [
        "focus:bg-bg-alt",
        "data-[state=open]:bg-bg-alt",
        "flex",
        "cursor-default",
        "select-none",
        "items-center",
        "rounded-sm",
        "px-2",
        "py-1.5",
        "text-sm",
        "outline-none",
      ],
      subtriggerIcon: ["ml-auto h-4 w-4"],
      subcontent: [
        "bg-surface-elevated",
        "text-text-em-mid",
        "z-dropdown",
        "min-w-[8rem]",
        "overflow-hidden",
        "rounded-md",
        "border",
        "p-1",
        "shadow-lg",
        "data-[state=open]:animate-in",
        "data-[state=closed]:animate-out",
        "data-[state=closed]:fade-out-0",
        "data-[state=open]:fade-in-0",
        "data-[state=closed]:zoom-out-95",
        "data-[state=open]:zoom-in-95",
        "data-[side=bottom]:slide-in-from-top-2",
        "data-[side=left]:slide-in-from-right-2",
        "data-[side=right]:slide-in-from-left-2",
        "data-[side=top]:slide-in-from-bottom-2",
      ],
      content: [
        "bg-surface-elevated",
        "text-text-em-mid",
        "z-dropdown",
        "min-w-[8rem]",
        "overflow-hidden",
        "rounded-md",
        "border",
        "p-1",
        "shadow-md",
        "data-[state=open]:animate-in",
        "data-[state=closed]:animate-out",
        "data-[state=closed]:fade-out-0",
        "data-[state=open]:fade-in-0",
        "data-[state=closed]:zoom-out-95",
        "data-[state=open]:zoom-in-95",
        "data-[side=bottom]:slide-in-from-top-2",
        "data-[side=left]:slide-in-from-right-2",
        "data-[side=right]:slide-in-from-left-2",
        "data-[side=top]:slide-in-from-bottom-2",
      ],
      item: [
        "focus:bg-bg-alt",
        "focus:text-text-on-secondary",
        "relative",
        "flex",
        "cursor-default",
        "select-none",
        "items-center",
        "rounded-sm",
        "px-2",
        "py-1.5",
        "text-sm",
        "outline-none",
        "transition-colors",
        "data-[disabled]:pointer-events-none",
        "data-[disabled]:opacity-50",
      ],
      checkboxItem: [
        "focus:bg-bg-alt",
        "focus:text-text-on-secondary",
        "relative",
        "flex",
        "cursor-default",
        "select-none",
        "items-center",
        "rounded-sm",
        "py-1.5",
        "pl-8",
        "pr-2",
        "text-sm",
        "outline-none",
        "transition-colors",
        "data-[disabled]:pointer-events-none",
        "data-[disabled]:opacity-50",
      ],
      checkboxItemIndicatorWrapper: [
        "absolute",
        "left-2",
        "flex",
        "h-3.5",
        "w-3.5",
        "items-center",
        "justify-center",
      ],
      checkboxItemCheckIcon: ["h-4", "w-4"],
      radioItem: [
        "focus:bg-bg-alt",
        "focus:text-text-on-secondary",
        "relative",
        "flex",
        "cursor-default",
        "select-none",
        "items-center",
        "rounded-sm",
        "py-1.5",
        "pl-8",
        "pr-2",
        "text-sm",
        "outline-none",
        "transition-colors",
        "data-[disabled]:pointer-events-none",
        "data-[disabled]:opacity-50",
      ],
      radioItemIndicatorWrapper: [
        "absolute",
        "left-2",
        "flex",
        "h-3.5",
        "w-3.5",
        "items-center",
        "justify-center",
      ],
      radioItemCheckIcon: ["h-4", "w-4", "fill-current"],
      label: ["px-2", "py-1.5", "text-sm", "font-semibold"],
      separator: ["bg-bg-alt", "-mx-1", "my-1", "h-px"],
      shortcut: ["ml-auto", "text-xs", "tracking-widest", "opacity-60"],
    },
    variants: {
      size: {
        md: {},
        sm: {},
      },
      inset: {
        true: {
          subcontent: ["pl-8"],
          item: ["pl-8"],
          label: ["pl-8"],
        },
      },
    },
  },
  { responsiveVariants: true },
);
