name: Tag Deployment Production Promotion
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing /
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Project Information
        run: |
          vercel pull \
          --yes \
          --environment=production \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --scope=${{ secrets.VERCEL_TEAM_NAME }}
      - name: Load Vercel Environment Variables into .env
        run: |
          vercel env pull .env \
          --yes \
          --environment=production \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --scope=${{ secrets.VERCEL_TEAM_NAME }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: |
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} >deployment-url.txt
          echo "deploymentUrl=$(cat deployment-url.txt)"
      - name: Promote new Production version
        run: |
          vercel promote $(cat deployment-url.txt) \
          --token=${{ secrets.VERCEL_TOKEN }} \
          --scope=${{ secrets.VERCEL_TEAM_NAME }}
